name: world_radio_app
description: A global radio streaming app built with Flutter.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  audioplayers: ^4.1.0

flutter:
  uses-material-design: true